# Generated by Django 6.1.1 on 2026-09-08 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_key', models.TextField(db_index=True)),
                ('quote', models.TextField()),
                ('prefix', models.TextField(blank=True, default='')),
                ('suffix', models.TextField(blank=True, default='')),
                ('color', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
