# Generated by Django 6.1.1 on 2026-09-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='highlights.catalog')),
            ],
        ),
    ]
