# Generated by Django 6.1.1 on 2026-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
