# Generated by Django 6.1.1 on 2026-09-09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def forwards_membership(apps, schema_editor):
    User = apps.get_model("identity", "User")
    Catalog = apps.get_model("highlights", "Catalog")
    Bookmark = apps.get_model("highlights", "Bookmark")
    Highlight = apps.get_model("highlights", "Highlight")
    CatalogMembership = apps.get_model("highlights", "CatalogMembership")

    user = User.objects.order_by("id").first()
    if user is None:
        return

    from highlights.page_key import page_identity_from_page_key

    bookmarked_ids = set(Bookmark.objects.values_list("catalog_id", flat=True))
    for catalog in Catalog.objects.all():
        CatalogMembership.objects.get_or_create(
            user=user,
            catalog=catalog,
            defaults={
                "title": catalog.title,
                "description": catalog.description,
                "bookmarked": catalog.id in bookmarked_ids,
            },
        )

    for highlight in Highlight.objects.all():
        identity = page_identity_from_page_key(highlight.page_key)
        catalog, _ = Catalog.objects.get_or_create(
            origin=identity.origin,
            path=identity.path,
            query=identity.query,
        )
        CatalogMembership.objects.get_or_create(
            user=user,
            catalog=catalog,
            defaults={
                "title": catalog.title,
                "description": catalog.description,
                "bookmarked": False,
            },
        )
        highlight.user_id = user.id
        highlight.catalog_id = catalog.id
        highlight.save(update_fields=["user_id", "catalog_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0004_catalog_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bookmarked", models.BooleanField(default=False)),
                ("title", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="highlights.catalog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="catalogmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "catalog"),
                name="catalogmembership_user_catalog",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="catalog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="highlights.catalog",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(forwards_membership, noop_reverse),
        migrations.AlterField(
            model_name="highlight",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="highlights.catalog",
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Bookmark",
        ),
        migrations.RemoveField(
            model_name="catalog",
            name="description",
        ),
        migrations.RemoveField(
            model_name="catalog",
            name="title",
        ),
    ]
