# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0005_catalog_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmembership",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
